#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!

#pod 'BTNavigationDropdownMenu'
#pod "OAuthSwift", "~> 0.4.6"
#pod 'Alamofire', '~> 3.0.0-beta.3'
pod 'SalesforceMobileSDK-iOS'
#pod 'Alamofire-SwiftyJSON', :git => 'https://github.com/SwiftyJSON/Alamofire-SwiftyJSON.git'
#pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
